name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v0.1.0)'
        required: true
        default: 'v0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build font
        run: npm run build-all

      - name: Create release archive
        run: |
          mkdir -p release/fukiai
          cp -r build/* release/fukiai/
          cp LICENSE.md release/fukiai/
          cp README.md release/fukiai/
          cd release
          zip -r fukiai-${{ github.event.inputs.version || github.ref_name }}.zip fukiai

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Fukiai ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            release/fukiai-${{ github.event.inputs.version || github.ref_name }}.zip
            build/fukiai.woff
            build/fukiai.ttf
            build/fukiai.svg
          body: |
            # Fukiai ${{ github.event.inputs.version || github.ref_name }}
            
            Modular icon font for synthesizer UIs and musical tools.
            
            ## Files included
            
            - SVG Font
            - TTF Font
            - WOFF Font
            - License
            - Documentation
            
            ## CDN Usage
            
            Use Fukiai via jsDelivr CDN:
            
            ```css
            @font-face {
              font-family: 'Fukiai';
              src: url('https://cdn.jsdelivr.net/gh/hugelton/Fukiai/releases/download/${{ github.event.inputs.version || github.ref_name }}/fukiai.woff') format('woff');
              font-weight: normal;
              font-style: normal;
            }
            ```
            
            ## Download and Self-hosting
            
            1. Download and extract the zip file
            2. Import the font in your CSS with `@font-face`
            3. Use the unicode values or class names to display icons
            
            ## Preview
            
            See the [preview page](https://hugelton.github.io/Fukiai/) for all available icons.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for jsDelivr CDN to refresh
        run: sleep 60

      - name: Verify jsDelivr CDN URL
        run: |
          VERSION="${{ github.event.inputs.version || github.ref_name }}"
          echo "Verifying jsDelivr CDN URL: https://cdn.jsdelivr.net/gh/hugelton/Fukiai/releases/download/$VERSION/fukiai.woff"
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://cdn.jsdelivr.net/gh/hugelton/Fukiai/releases/download/$VERSION/fukiai.woff" || echo "Error")
          echo "Response code: $RESPONSE_CODE"
          
          if [[ $RESPONSE_CODE == "200" ]]; then
            echo "✅ jsDelivr CDN URL is accessible!"
          else
            echo "⚠️ jsDelivr CDN URL may not be available yet. This is normal and should be available soon."
          fi
