name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v0.1.0)'
        required: true
        default: 'v0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build font
        run: npm run build-all

      - name: Create release archive
        run: |
          mkdir -p release/fukiai
          cp -r build/* release/fukiai/
          cp LICENSE.md release/fukiai/
          cp README.md release/fukiai/
          cd release
          zip -r fukiai-${{ github.event.inputs.version || github.ref_name }}.zip fukiai

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Fukiai ${{ github.event.inputs.version || github.ref_name }}
          draft: false
          prerelease: false
          files: |
            release/fukiai-${{ github.event.inputs.version || github.ref_name }}.zip
          body: |
            # Fukiai ${{ github.event.inputs.version || github.ref_name }}
            
            Modular icon font for synthesizer UIs and musical tools.
            
            ## Files included
            
            - SVG Font
            - TTF Font
            - WOFF Font
            - License
            - Documentation
            
            ## How to use
            
            1. Download and extract the zip file
            2. Import the font in your CSS with `@font-face`
            3. Use the unicode values or class names to display icons
            
            ## Preview
            
            See the [preview page](https://hugelton.github.io/Fukiai/) for all available icons.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
