name: Release Fukiai Font

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip font files
        run: |
          mkdir -p dist
          zip -j dist/fukiai-font.zip build/fukiai.*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: font-release-${{ github.run_number }}
          name: Fukiai Font Release ${{ github.run_number }}
          files: dist/fukiai-font.zip
