name: Release and Deploy (No Artifacts)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build font
        run: npm run build-all

      - name: Create release archive
        run: |
          mkdir -p release/fukiai
          cp -r build/* release/fukiai/
          cp LICENSE.md README.md release/fukiai/
          cd release
          zip -r fukiai-${{ github.ref_name }}.zip fukiai
          cd ..

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/fukiai-${{ github.ref_name }}.zip
          tag: ${{ github.ref_name }}
          name: Fukiai ${{ github.ref_name }}
          body: |
            # Fukiai ${{ github.ref_name }}

            Modular icon font for synthesizer UIs and musical tools.

            See the preview at: https://hugelton.github.io/Fukiai/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
